unique_ids:
  assets:
    standard-page.html: PMVL4WFZBS7H2ZV4ZDJWKUKA3YYVDHYJ
    theme.css: ONQ6H3MIX2T2MDW5ZKTLBXPCWPGSUGC6
  forms:
    Form1: XBKFSYZ44TF6OM24J7F3K5RXG6VY3ZLO
    Form1.ItemTemplate1: '1749159525492919980137433.5166'
    Form1.RowTemplate1: '174915955040878865840661.80835'
  modules: {}
  scripts: {}
  server_modules: {}
